# Generated by Django 3.0.4 on 2020-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='+84', max_length=15),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.IntegerField(choices=[(-1, 'Nữ'), (0, 'Không xác định'), (1, 'Nam')], default=0),
        ),
    ]
