# Generated by Django 3.0.4 on 2020-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200324_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_verified',
            new_name='is_active_email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active_phone',
            field=models.BooleanField(default=False),
        ),
    ]
