# Generated by Django 3.0.4 on 2020-04-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200412_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_categoty',
            new_name='slug_category',
        ),
    ]
