# Generated by Django 3.0.4 on 2020-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200412_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug_product',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
