# Generated by Django 3.0.4 on 2020-05-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200412_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productpictures',
            name='image_product',
            field=models.ImageField(upload_to='product-pictures/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_picture',
            field=models.ImageField(default='no-img.png', null=True, upload_to='main-product-pictures/'),
        ),
    ]
