# Generated by Django 3.0.4 on 2020-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200514_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='no-img.png', null=True, upload_to='category-pictures/'),
        ),
    ]
